service: back-gestor
env: standard
#env: flex
runtime: java17
#runtime: java
#runtime_config:
#  jdk: openjdk-17-jdk
entrypoint: java -Xmx100m -jar gestordocumenta-0.0.1.jar
#entrypoint: target/gestordocumenta-0.0.1.jar
instance_class: F1
#handlers:
#  - url: /.*
#    script: this field is required, but ignored
#manual_scaling:
 # instances: 1
#basic_scaling:
#  max_instances: 1
  #idle_timeout: 5m
automatic_scaling:
  max_instances: 1
  min_instances: 1
  min_idle_instances: 0
  max_idle_instances: 0
  #idle_timeout: 100m
inbound_services:
  - warmup
